# Generated by Django 3.0.8 on 2020-07-10 00:32

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('funcao', models.CharField(max_length=90)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='fotos/perfil/%d/%m/%Y/')),
                ('linkedin', models.URLField(blank=True)),
                ('git_hub', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
