# Generated by Django 3.0.8 on 2020-07-12 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('funcao', models.CharField(max_length=90)),
                ('foto_perfil', models.ImageField(blank=True, upload_to='fotos/perfil/%d/%m/%Y/')),
                ('linkedin', models.URLField(blank=True)),
                ('git_hub', models.URLField(blank=True)),
            ],
        ),
    ]
