# Generated by Django 3.0.8 on 2020-07-13 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Portifolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortifolioItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('foto', models.ImageField(upload_to='fotos/portifolio/%d/%m/%Y/<django.db.models.fields.related.ForeignKey>/item')),
                ('descricao', models.TextField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
