# Generated by Django 3.0.8 on 2020-07-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portifolio', '0002_portifolioitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolioitem',
            name='foto',
            field=models.ImageField(upload_to="fotos/portifolio/%d/%m/%Y/<class 'django.contrib.auth.models.User'>/item"),
        ),
    ]
