# Generated by Django 3.0.8 on 2020-07-13 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portifolio', '0003_auto_20200712_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolioitem',
            name='foto',
            field=models.ImageField(upload_to='fotos/portifolio/%d/%m/%Y/<property object at 0x04076280>/item'),
        ),
    ]
