# Generated by Django 3.0.8 on 2020-07-13 01:28

import apps.Portifolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portifolio', '0004_auto_20200712_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portifolioitem',
            name='foto',
            field=models.ImageField(upload_to=apps.Portifolio.models.upload_to_item),
        ),
    ]
