# Generated by Django 3.0.8 on 2020-07-13 01:32

import apps.Portifolio.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portifolio', '0005_auto_20200712_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='portifolioitem',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 7, 12, 22, 32, 59, 136786)),
        ),
        migrations.AlterField(
            model_name='portifolioitem',
            name='foto',
            field=models.ImageField(blank=True, upload_to=apps.Portifolio.models.upload_to_item),
        ),
    ]
