# Generated by Django 3.0.8 on 2020-07-16 19:28

import apps.Portifolio.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Portifolio', '0006_auto_20200712_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='imagem',
            field=models.FileField(blank=True, upload_to=apps.Portifolio.models.upload_to_portifolio),
        ),
        migrations.AlterField(
            model_name='portifolioitem',
            name='data',
            field=models.DateField(default=datetime.datetime(2020, 7, 16, 16, 28, 10, 67468)),
        ),
        migrations.CreateModel(
            name='SobreVoce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
